### ISSUE TITLE
Game disappeared then appeared again

### ISSUE THREAD

**Issue by dcms2** [openingtree/openingtree#269]
There was only a single game, I made the move from the game, it showed 2 new games, none of which was the original game, then after doing another move, the original game showed up. How can this be possible?

Lichess name: duhancaraciolo, blitz, playing as white.

Moves: 
1. d4 d5
2. Bf4 Nf6
3. Nf3 e6
4. e3 c5 (after c5, four games turn into a single one, let's call it X)
Now, the next move in that only game is c3, but...
5. c3 ... (the game is replaced by two separate other ones, let's call them Y and Z)
5. ... Nc6 (now we have games X and Y, both of which are followed by Bd3)
6. Bd3 ... (we still have X and Y, now split up into different moves)

What happened with game X after c3 in move 5? Shouldn't we either show X, Y and Z, or group X with either Y or Z?

Thanks for the tool!

**Comment by vjuneja** [comment]
Thanks for reporting this. I just checked and it seems like an issue.

**Comment by vjuneja** [comment]
fixed with this
https://github.com/openingtree/openingtree/commit/fafc978b9685c83f80fa7a3c591d84404ca87e00

**Comment by vjuneja** [comment]
@dcms2 I have deployed a fix to [https://www.openingtree.com/latest
](https://www.openingtree.com/latest) This was more of a display issue rather than actual logic. the base problem was transpositions happening in the position. Would appreciate if you would try it out because there is a chance the fix is more confusing than the actual problem :)

**Comment by vjuneja** [comment]
https://github.com/openingtree/openingtree/pull/276
